[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#252729ff"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
runOnSave = true